apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-hello-chart.fullname" . }}-configmap
data:
  index.html: |
    <html>
    <head>
      <title>Hello, helm!</title>
    </head>
    <body>
      <h1>Hello, helm!</h1>
    </body>
    </html>