apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-hello-chart.fullname" . }}
  labels:
    {{- include "nginx-hello-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-hello-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nginx-hello-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: site-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: site-content
          configMap:
            name: {{ include "nginx-hello-chart.fullname" . }}
            defaultMode: 420
